function getLanguageName(languageCode) {
    const languageMap = {
        en: 'English',
        es: 'Spanish',
        fr: 'French',
        de: 'German',
        ja: 'Japanese',
        zh: 'Chinese',
        ko: 'Korean',
        it: 'Italian',
        ru: 'Russian',
        hi: 'Hindi',
        pt: 'Portuguese',
        ar: 'Arabic',
        tr: 'Turkish',
        th: 'Thai',
        id: 'Indonesian',
        nl: 'Dutch',
        sv: 'Swedish',
        pl: 'Polish',
        da: 'Danish',
        no: 'Norwegian',
        fi: 'Finnish',
        he: 'Hebrew',
        el: 'Greek',
        cs: 'Czech',
        hu: 'Hungarian',
        ro: 'Romanian',
        vi: 'Vietnamese',
        bg: 'Bulgarian',
        sr: 'Serbian',
        sk: 'Slovak',
        sl: 'Slovenian',
        et: 'Estonian',
        lv: 'Latvian',
        lt: 'Lithuanian',
        hr: 'Croatian',
        bn: 'Bengali',
        ur: 'Urdu',
        fa: 'Persian',
        ms: 'Malay',
        tl: 'Tagalog',
    };

    return languageMap[languageCode] || languageCode; // Return the language name or code if not found
}